[package]
name = "bitfrob"
description = "Helps you frob those bits"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Lokathor/bitfrob"
license = "Zlib OR Apache-2.0 OR MIT"
categories = ["no-std"]

[dependencies]
# none!
