[package]
name = "bitfrob"
description = "Helps you frob those bits"
version = "0.2.2"
edition = "2021"
repository = "https://github.com/Lokathor/bitfrob"
license = "Zlib OR Apache-2.0 OR MIT"
categories = ["no-std"]

[dependencies]
# none!

[features]
track_caller = [] # adds `track_caller` attribute on fns that assert things. This can mess up inlining, probably only use this for debugging.
